GENERAL:
    mode: "GAN" # choices 'det' 'GAN' 'VAEGAN'
    problem_type: "normal" # choices 'normal' 'superresolution'
    
MODEL:
    architecture: "normal"
        
SETUP:
    log_folder: "/ppdata/lucy-cGAN/logs/IFS"

GENERATOR:
    filters_gen: 128
    noise_channels: 4 # used for GAN
    latent_variables: 1 # used for VAEGAN
    learning_rate_gen: 1e-5

DISCRIMINATOR:
    filters_disc: 512
    learning_rate_disc: 1e-5

TRAIN:
    train_years: [2016, 2017, 2018] 
    training_weights: [0.4, 0.3, 0.2, 0.1]
    num_samples: 320000
    steps_per_epoch: 800
    batch_size: 16
    kl_weight: 1e-8 # used for VAEGAN

VAL:
    val_years: 2019 # cannot pass a list if using create_fixed_dataset
    val_size: 8

EVAL:
    num_batches: 256
    add_postprocessing_noise: True # flag for adding postprocessing noise in rank statistics eval
    postprocessing_noise_factor: 1e-6 # factor for scaling postprocessing noise in rank statistics eval